### ISSUE TITLE
How should I use your code based on my dataset?

### ISSUE THREAD

**Issue by ZhenWusi** [xuhangc/Sea-thru-implementation#1]
How to run the code, what the depth folder looks like, how to get it

**Comment by xuhangc** [comment]
`python seathru.py` should be able to run the code. You may need to install some required packages before you run the code. Depth map can be generated by different methods, you may refer to depth estimation for more detailed information.

**Comment by ZhenWusi** [comment]
Can you provide a way to get the depth map, or can you provide your dataset format？thank you very much

**Comment by xuhangc** [comment]
> Can you provide a way to get the depth map, or can you provide your dataset format？thank you very much

This is a repo for depth map generation [Depth map Repo](https://github.com/CXH-Research/Depth-Map-and-Transmission-Map-Generation).

Below is a dataset folder structure for example. Make sure the corresponding uw_img and depth_map share the same name and extension.
```
.
└── dataset/
    ├── input/
    │   └── uw_img
    └── depth/
        └── depth_map
```

**Comment by ZhenWusi** [comment]
Thank you very much?I will try it.
