### ISSUE TITLE
Requirements for the script

### ISSUE THREAD

**Issue by lalafreguete** [xuhangc/Sea-thru-implementation#2]
Good morning.
I'm interested in implementing this algorithm for a master's research and I'm wondering if you could provide some tips on using it, especially for beginners like me.
I read the paper that explains the theory for the algorithm, but it kept me wondering about two things:
1) Do I need the color charts for running this script?
2) How can I do camera calibration before the underwater survey with the camera?
Do you have experience with it? Please share some tips about it.
I see this repository has only the seathru.py script in comparison to the hainh's one. Would only the seathru.py suffice? Or would I need the other scripts provided on hainh's repository?
Sorry for all these questions, but I would really appreciate any help with it.
Many thanks!

**Comment by xuhangc** [comment]
1. I think the color charts are for the ground truth image obtaining. This script is for underwater image enhancement and dont need color charts.
2. If you want to do camera calibration, you may need some preprocessing in Adobe Photoshop or rawpy. Basically it is about the whole ISP process and you can refer to some computational photography resources. seathru.py requires depth maps, I can adopt a simple depth map generation method. I think it will perform better if you can use better depth estimation algorithm.
